# Generated by Django 5.2.2 on 2025-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='UserID')),
                ('username', models.CharField(max_length=30, verbose_name='Full Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Visit Count')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
                ('joined_ip', models.GenericIPAddressField(verbose_name='Join IP Address')),
            ],
        ),
    ]
