# Generated by Django 5.2.2 on 2025-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='UserID')),
                ('username', models.CharField(max_length=50, verbose_name='Full Name')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Password')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Phone Number')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Visit Count')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
                ('joined_ip', models.CharField(max_length=50, null=True, verbose_name='Join IP Address')),
            ],
        ),
    ]
