# Generated by Django 5.2.2 on 2025-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('user_review_count', models.IntegerField(verbose_name='User Review Count')),
                ('blog_review_count', models.IntegerField(verbose_name='Blog Review Count')),
                ('reservation_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reservation Site')),
            ],
        ),
    ]
