# Generated by Django 5.2.2 on 2025-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
