# Generated by Django 5.2.2 on 2025-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_joined_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_ip',
            field=models.GenericIPAddressField(auto_created=True, blank=True, null=True),
        ),
    ]
