# Generated by Django 5.2.2 on 2025-06-15 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_chatsession_user_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in Session')),
                ('sender', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], default='user', help_text="메시지 발신 주체. 'user' 또는 'assistant'", max_length=20, verbose_name='Chat Sender')),
                ('text', models.TextField(blank=True, verbose_name='Text Content')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('llm_request', models.JSONField(verbose_name='LLM Request Payload')),
                ('llm_response', models.JSONField(verbose_name='LLM Response Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='api.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=50, verbose_name='Component Type')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in Message')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('chat_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Chat Session Title')),
                ('info', models.TextField(null=True, verbose_name='Chat Session Info')),
                ('session_parameters', models.JSONField(blank=True, default=dict, help_text='장소, 일정, 인원, 컨셉 등 세션 공통 파라미터', verbose_name='Session Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession'),
        ),
        migrations.CreateModel(
            name='ChatSessionSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_text', models.TextField(verbose_name='Summary Text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='MessageEmbedding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vector', models.JSONField(verbose_name='Embedding Vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='api.chatmessage')),
            ],
        ),
    ]
