# Generated by Django 5.2.2 on 2025-06-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatmessage_chatinteraction_chatcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinteraction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='messageembedding',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatsessionsummary',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatComponent',
        ),
        migrations.DeleteModel(
            name='ChatInteraction',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='MessageEmbedding',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='ChatSessionSummary',
        ),
    ]
