# Generated by Django 5.2.2 on 2025-06-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatmessage_chatinteraction_chatcomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='phone_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Phone Number'),
        ),
    ]
