# Generated by Django 5.2.2 on 2025-06-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
